- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.1
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: detect-private-key

- repo: git://github.com/kintoandar/pre-commit.git
  sha: v2.1.0
  hooks:
  - id: terraform_validate
